name: Integration Test Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Integration tests
        run: |
          cd ./eyesonly/tests/integration
          make run

